# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travelog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travelog
  platform :ios, '14.0'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


  target 'TravelogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelogUITests' do
    # Pods for testing
  end

end
